# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Test, Lint, and Build

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      checks: write
      pull-requests: write
      security-events: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'

      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: Run ESLint
        continue-on-error: true
        run: |
          yarn lint --max-warnings=0 --format @microsoft/eslint-formatter-sarif --output-file eslint-results.sarif

      - name: Upload ESLint results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true

      - name: Run type checks
        run: yarn typecheck

      - name: Run tests
        run: yarn test:ci

  playwright-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      - name: Get playwright version
        id: playwright-version
        run: |
          VERSION=$(yarn info playwright version -s)
          echo "Setting PLAYWRIGHT_VERSION to $VERSION"
          echo "PLAYWRIGHT_VERSION=$VERSION" >> $GITHUB_ENV
      - name: Cache playwright binaries
        uses: actions/cache@v4
        id: cache-playwright
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}-
      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
        if: steps.cache-playwright.outputs.cache-hit != 'true'
      - name: Install Playwright Browsers
        run: yarn playwright install-deps
        if: steps.cache-playwright.outputs.cache-hit == 'true'
      - name: Run Playwright tests
        run: yarn playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs:
      - lint-and-test
      - playwright-test
    strategy:
      matrix:
        dockerfile: [Frontend.Dockerfile, Playwright.Dockerfile]
      fail-fast: false
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Dockerfile Name
        id: dockerfile
        run: |
          name=$(echo ${{ matrix.dockerfile }} | cut -d'.' -f1)
          name=$(echo $name | tr '[:upper:]' '[:lower:]')
          echo "Name: $name"
          image_name="commanderred42/webstore-$name"
          echo "Image Name: $image_name"
          echo "image_name=$image_name" >> $GITHUB_ENV

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          flavor: |
            latest=true
          images: ${{ env.image_name }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
